import { NavMenuItemProps, NavSubMenuProps } from "@/types/type";

export const NavMenu = {
  area: [
    { title: "유연한 검색", image: "/RegionImage/world.jpg", word: "" },
    { title: "유럽", image: "/RegionImage/europ.webp", word: "europ" },
    { title: "일본", image: "/RegionImage/japan.jpg", word: "japan" },
    {
      title: "동남아시아",
      image: "/RegionImage/eastAsia.webp",
      word: "eastAsia",
    },
  ] as Array<NavMenuItemProps>,
  korea: [
    { title: "서울", word: "seoul" },
    { title: "부산", word: "busan" },
    { title: "제주도", word: "jeju island" },
    { title: "속초", word: "sokcho" },
    { title: "강릉", word: "gangneung" },
    { title: "전주", word: "jeonju" },
    { title: "대구", word: "daegu" },
    { title: "경주", word: "gyeongju" },
    { title: "여수", word: "yeosu" },
    { title: "서귀포", word: "seogwipo" },
    { title: "대전", word: "daejeon" },
    { title: "인천", word: "incheon" },
  ] as Array<NavMenuItemProps>,
};

export const SubNavMenu: Array<NavSubMenuProps> = [
  {
    title: "전 세계",
    inventory: [
      { title: "오사카", word: "osaka" },
      { title: "도쿄", word: "tokyo" },
      { title: "후쿠오카", word: "fukuoka" },
      { title: "방콕", word: "bangkok" },
      { title: "런던", word: "london" },
      { title: "치앙마이", word: "chiangmai" },
      { title: "타이페이", word: "taipei" },
      { title: "시드니", word: "sydney" },
      { title: "삿포로", word: "sapporo" },
      { title: "그린델발트", word: "grindelwald" },
      { title: "바르셀로나", word: "barcelona" },
      { title: "인터라켄", word: "interlaken" },
    ],
  },
  {
    title: "동아시아",
    inventory: [
      { title: "오사카", word: "osaka" },
      { title: "도쿄", word: "tokyo" },
      { title: "후쿠오카", word: "fukuoka" },
      { title: "타이페이", word: "taipei" },
      { title: "삿포로", word: "sapporo" },
      { title: "오키나와", word: "okinawa" },
      { title: "교토", word: "kyoto" },
      { title: "나고야", word: "nagoya" },
      { title: "벳푸", word: "beppu" },
      { title: "유후", word: "yoohoo" },
      { title: "히로시마", word: "hiroshima" },
      { title: "나하", word: "naha" },
    ],
  },
  {
    title: "동남아시아",
    inventory: [
      { title: "방콕", word: "bangkok" },
      { title: "차앙마이", word: "chaang Mai" },
      { title: "하노이", word: "hanoi" },
      { title: "파타야", word: "pattaya" },
      { title: "나짱", word: "nha trang" },
      { title: "세부", word: "cebu" },
      { title: "호이안", word: "hoian" },
      { title: "달랏", word: "dalat" },
      { title: "다낭", word: "da nang" },
      { title: "마닐라", word: "manila" },
      { title: "엔젤레스", word: "angeles" },
      { title: "코타키나발루", word: "kota kinabalu" },
    ],
  },
  {
    title: "유럽",
    inventory: [
      { title: "런던", word: "london" },
      { title: "그린델발트", word: "grindelwald" },
      { title: "바르셀로나", word: "barcelona" },
      { title: "인터라켄", word: "interlaken" },
      { title: "프라하", word: "prague" },
      { title: "세비야", word: "seville" },
      { title: "파리", word: "paris" },
      { title: "부다페스트", word: "budapest" },
      { title: "마드리드", word: "madrid" },
      { title: "리스본", word: "lisbon" },
      { title: "빈", word: "vin" },
      { title: "나스", word: "nas" },
    ],
  },
  {
    title: "아메리카 대륙",
    inventory: [
      { title: "로스엔젤레스", word: "los angeles" },
      { title: "호놀룰루", word: "honolulu" },
      { title: "뉴욕", word: "new york" },
      { title: "밴쿠버", word: "vancouver" },
      { title: "라스베이거스", word: "las vegas" },
      { title: "토론토", word: "toronto" },
      { title: "카일루아코아", word: "kailuakoa" },
      { title: "조슈아 트리", word: "joshua tree" },
      { title: "샌프란시스코", word: "san francisco" },
      { title: "샌디에이고", word: "san diego" },
      { title: "힐로", word: "hilo" },
      { title: "보스턴", word: "boston" },
    ],
  },
  {
    title: "오세아니아",
    inventory: [
      { title: "시드니", word: "sydney" },
      { title: "멜버른", word: "melbourne" },
      { title: "와나카", word: "wanaka" },
      { title: "오클랜드", word: "auckland" },
      { title: "브리즈번", word: "brisbane" },
      { title: "크라이스트처치", word: "christchurch" },
      { title: "골드코스트", word: "gold coast" },
      { title: "테아나우", word: "te anau" },
      { title: "브리즈번", word: "Brisbane" },
      { title: "테카포 호수", word: "lake tekapo" },
      { title: "서리 힐스", word: "surry hills" },
      { title: "해밀턴", word: "hamilton" },
    ],
  },
  {
    title: "아시아의 다른지역",
    inventory: [
      { title: "이스탄불", word: "istanbul" },
      { title: "울란바토르", word: "ulaanbaatar" },
      { title: "안탈리아", word: "antalya" },
      { title: "알마티", word: "almaty" },
      { title: "트빌리", word: "tbili" },
      { title: "아부다비", word: "abu dhabi" },
      { title: "이즈미르", word: "izmir" },
      { title: "암만", word: "amman" },
      { title: "콜롬보", word: "colombo" },
      { title: "앙카라", word: "ankara" },
      { title: "파묵칼레", word: "pamukkale" },
      { title: "카스", word: "cass" },
    ],
  },
  {
    title: "아프리카",
    inventory: [
      { title: "카이로", word: "cairo" },
      { title: "케이프타운", word: "cape town" },
      { title: "룩소르", word: "luxor" },
      { title: "마라케", word: "marrakech" },
      { title: "카사블랑카", word: "casablanca" },
      { title: "알렉산드리아", word: "alexandria" },
      { title: "탕헤르", word: "tangier" },
      { title: "라바트", word: "rabat" },
      { title: "다합", word: "dahab" },
      { title: "나이로비", word: "nairobi" },
      { title: "후르가다", word: "hurghada" },
      { title: "페스", word: "fes" },
    ],
  },
];

export const getMonth = () => {
  const month = [];
  for (let i = 0; i < 12; i++) {
    const now = new Date();
    const mon = new Date(now.setMonth(now.getMonth() + i));
    month.push(mon);
  }
  return month;
};

export const country = [
  { name: "콩고 (+242)", number: 242 },
  { name: "콩고 민주 공화국 (+243)", number: 243 },
  { name: "코소보 (+383)", number: 383 },
  { name: "북마케도니아 (+389)", number: 389 },
  { name: "가나 (+233)", number: 233 },
  { name: "가봉 (+241)", number: 241 },
  { name: "가이아나 (+592)", number: 592 },
  { name: "감비아 (+220)", number: 220 },
  { name: "건지 (+44)", number: 44 },
  { name: "과들루프 (+590)", number: 590 },
  { name: "과테말라 (+502)", number: 502 },
  { name: "괌 (+1)", number: 1 },
  { name: "그레나다 (+1)", number: 1 },
  { name: "그리스 (+30)", number: 30 },
  { name: "그린란드 (+299)", number: 299 },
  { name: "기니 (+244)", number: 244 },
  { name: "기니비사우 (+245)", number: 245 },
  { name: "나미비아 (+264)", number: 264 },
  { name: "나우루 (+674)", number: 674 },
  { name: "나이지리아 (+234)", number: 234 },
  { name: "남수단 (+211)", number: 211 },
  { name: "남아프리카 (+27)", number: 27 },
  { name: "네덜란드 (+31)", number: 31 },
  { name: "네덜란드령 카리브 (+599)", number: 599 },
  { name: "네팔 (+977)", number: 977 },
  { name: "노르웨이 (+47)", number: 47 },
  { name: "노퍽섬 (+672)", number: 672 },
  { name: "뉴질랜드 (+64)", number: 64 },
  { name: "뉴칼레도니아 (+687)", number: 687 },
  { name: "니우에 (+683)", number: 683 },
  { name: "니제르 (+227)", number: 227 },
  { name: "니카라과 (+505)", number: 505 },
  { name: "덴마크 (+45)", number: 45 },
  { name: "도미니카 (+1)", number: 1 },
  { name: "도미니카 공화국 (+1)", number: 1 },
  { name: "독일 (+49)", number: 49 },
  { name: "동티모르 (+670)", number: 670 },
  { name: "라오스 (+856)", number: 856 },
  { name: "라이베리아 (+231)", number: 231 },
  { name: "라트비아 (+371)", number: 371 },
  { name: "러시아 (+7)", number: 7 },
  { name: "레바논 (+961)", number: 961 },
  { name: "레소토 (+266)", number: 266 },
  { name: "루마니아 (+40)", number: 40 },
  { name: "룩셈부르크 (+352)", number: 352 },
  { name: "르완다 (+250)", number: 250 },
  { name: "리비아 (+218)", number: 218 },
  { name: "리투아니아 (+370)", number: 370 },
  { name: "리히텐슈타인 (+423)", number: 423 },
  { name: "마다가스카르 (+261)", number: 261 },
  { name: "말라위 (+265)", number: 265 },
  { name: "말레이시아 (+60)", number: 60 },
  { name: "말리 (+223)", number: 223 },
  { name: "멕시코 (+52)", number: 52 },
  { name: "모나코 (+377)", number: 377 },
  { name: "모로코 (+212)", number: 212 },
  { name: "몽골 (+976)", number: 976 },
  { name: "미국 (+1)", number: 1 },
  { name: "미얀마 (+95)", number: 95 },
  { name: "방글라데시 (+880)", number: 880 },
  { name: "베트남 (+84)", number: 84 },
  { name: "브라질 (+55)", number: 55 },
  { name: "사우디아라비아 (+966)", number: 966 },
  { name: "스웨덴 (+46)", number: 46 },
  { name: "스위스 (+41)", number: 41 },
  { name: "스페인 (+34)", number: 34 },
  { name: "싱가포르 (+65)", number: 65 },
  { name: "아랍에미리트 (+971)", number: 971 },
  { name: "영국 (+44)", number: 44 },
  { name: "우크라이나 (+380)", number: 380 },
  { name: "일본 (+81)", number: 81 },
  { name: "중국 (+86)", number: 86 },
  { name: "캐나다 (+1)", number: 1 },
  { name: "태국 (+66)", number: 66 },
  { name: "터키 (+90)", number: 90 },
  { name: "파키스탄 (+92)", number: 92 },
  { name: "프랑스 (+33)", number: 33 },
  { name: "필리핀 (+63)", number: 63 },
  { name: "한국 (+82)", number: 82 },
  { name: "홍콩 (+852)", number: 852 },
];

export const getYears = () => {
  const today = new Date();
  const years: Array<number> = [];
  for (let i = today.getFullYear(); i >= 1900; i--) {
    years.push(i);
  }
  return years;
};
